### Create message
POST https://minimal-server-six.vercel.app/api/messages
Content-Type: application/json

{
    "name": "Lordem",
    "email": "lord@mail.com",
    "message": "Acept the revenge of my wrath"
}

### Get messages
GET https://minimal-server-six.vercel.app/api/messages


### Init Root
GET https://minimal-server-six.vercel.app/