### Create message
POST https://minimal-server-six.vercel.app/api/messages
Content-Type: application/json

{
    "name": "Meriadox",
    "email": "merrino@gmail.com",
    "message": "lust od death rising",
}