### Create message
POST https://minimal-server-six.vercel.app/api/messages
Content-Type: application/json

{
    "name": "Lordem",
    "email": "lord@mail.com",
    "message": "Acept the revenge of my wrath"
}

### Get messages
GET https://minimal-server-six.vercel.app/api/messages


### Init Root
GET https://minimal-server-six.vercel.app/


### Post in to VPS
POST http://customer-eg.online/api/messages
Content-Type: application/json

{ 
    "nombre": "nombre",
    "apellido": "apellido",
    "email": "user@example.com",
    "profesion": "profesion",
    "empresa": "empresa",
    "pais": "pais"
}

### Post in to Epikka DB
POST http://localhost:4000/api/epikka
Content-Type: application/json

{ 
    "nombre": "nombre",
    "email": "user@example.com",
    "telefono": "0303456",
    "mensaje": "Es un test de mensajes, no tomar en cuenta."
}


### Post informes
POST http://localhost:4000/api/informes
Content-Type: application/json

{ 
    "latitud": "-34.55217",
    "longitud": "-58.69784",
    "label_1": "label_1",
    "conf_1": "conf_1",
    "label_2": "label_2",
    "conf_2": "conf_2"
}


### Get informes
GET http://localhost:4000/api/informes